import fs from 'node:fs';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import ts from 'typescript';
const load = path => {
 const module={exports:{}};
 vm.runInNewContext(ts.transpile(fs.readFileSync(path,'utf8'),{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}),{module,exports:module.exports,require:name=>name==='./attributeFilters'?load('src/utils/attributeFilters.ts'):null,console});
 return module.exports;
};
const {restoreTemplate,validateProbeDependencies,exportAttribute}=load('src/utils/probeConfig.ts');
const fixture={extracts:{target_region:{source:'exon',length:40,overlap:0}},probes:{pad:{template:'{part1}',parts:{part1:{expr:'target_region',attributes:{kmer_count:{enabled:true,kmer_len:21,aligner:'Jellyfish'}}}}}},attributes:{a:{target:'target_region',type:'fold_score'},b:{target:'pad.part1',type:'annealing_temperature'},c:{target:'pad.part1',type:'annealing_temperature'}},post_process:{filters:{a:{condition:'a <= 0'},b:{condition:'b > 36 & b <= 44'},ends:{type:'sequence_pattern',target:'pad',exclude_patterns:['(?P<base>[ACGT])(?P=base){3,}']},composite:{condition:'a < 1 | b > 40'}},sorts:{is_ascending:['a'],is_descending:['b']}}};
const before=JSON.stringify(fixture);const result=restoreTemplate(fixture);
assert.equal(JSON.stringify(fixture),before,'hydration must not mutate the template');
assert.equal(result.targetConfig.attributes.foldScore.max,0);
assert.equal(result.probes.pad.parts.part1.attributes.tm.minInclusive,false);
assert.equal(result.probes.pad.parts.part1.attributes.c.originalName,'c','multiple attributes of same type retained');
assert.equal(result.probes.pad.parts.part1.attributes.kmer_count.kmer_len,21);
assert.equal(result.sortDefaults[0].field,'a');assert.equal(result.sortDefaults[1].order,'desc');
assert.equal(result.extraFilters.ends.exclude_patterns[0],fixture.post_process.filters.ends.exclude_patterns[0]);
assert.equal(result.extraFilters.composite.condition,fixture.post_process.filters.composite.condition);
assert.throws(()=>restoreTemplate({...fixture,attributes:{bad:{target:'missing.part',type:'fold_score'}}}),/missing sequence/);
assert.equal(validateProbeDependencies([{id:'1',name:'one',parts:[]},{id:'2',name:'two',parts:[{source:'probe',sourceProbeId:'1'}]}]),'');
assert.match(validateProbeDependencies([{id:'1',name:'same'},{id:'2',name:'same'}]),/unique/);
assert.match(validateProbeDependencies([{id:'1',parts:[{source:'probe',sourceProbeId:'2'}]},{id:'2',parts:[{source:'probe',sourceProbeId:'1'}]}]),/cycle/);
assert.match(validateProbeDependencies([{id:'1',parts:[{source:'probe',sourceProbeId:'missing'}]}]),/exist/);
console.log('PASS: template hydration, duplicate attributes, filters, sorting, Python regex preservation and probe dependency validation');

assert.equal(exportAttribute({kmer_len:21,aligner:'Jellyfish'},'kmer_count','pad.part1').kmer_len,21);
assert.equal(exportAttribute({kmer_len:21,aligner:'Jellyfish'},'kmerCount','pad.part1').type,'kmer_count');
assert.equal(exportAttribute({originalType:'fold_score'},'custom_score','probe12').target,'probe12');
assert.equal(exportAttribute({min_mapq:0,aligner:'Bowtie2'},'mapped_genes','target_region').min_mapq,0);
import { createRequire } from 'node:module';
const require=createRequire(import.meta.url);
const yaml=require('js-yaml');
const customSource=fs.readFileSync('src/pages/CustomProbe.tsx','utf8');
const start=customSource.indexOf('const convertProbesToYAML =');
const end=customSource.indexOf('const CustomProbe:',start);
const context={yaml,result:null,console};
vm.runInNewContext(ts.transpile(customSource.slice(start,end)+'\nglobalThis.convert=convertProbesToYAML;',{target:ts.ScriptTarget.ES2020}),context);
const serialized=context.convert([{id:'one',name:'pad',isComplete:true,parts:[{source:'barcode',label:'barcode: BC1',sequence:'ACGT'},{source:'fixed',sequence:'AT'}],attributes:{fold_score:{enabled:true,max:10}}}],40,{BC1:''},{BC1:4},{source:'exon',length:40,sequence:'',attributes:{tm:{enabled:true,min:36,max:44}}});
const decoded=yaml.load(serialized);const hydrated=restoreTemplate(decoded);
assert.equal(decoded.barcodes.barcodes.BC1.length,4);
assert.equal(hydrated.probes.pad.parts.part1.expr,"encoding[target]['BC1']");
assert.equal(hydrated.probes.pad.attributes.fold_score.max,10);
assert.equal(hydrated.targetConfig.attributes.tm.min,36);
const serializedAgain=context.convert([{id:'one',name:'pad',isComplete:true,parts:[],attributes:{}}],40,{BC1:''},{},{source:'exon',length:40,sequence:'',attributes:{}});
assert.equal(yaml.load(serializedAgain).barcodes.barcodes.BC1.length,undefined);
console.log('PASS: actual custom-template YAML serializer and workflow hydration');
